name: NuxtHub Build (SSG)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build Nuxt 3 SSG
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'    # ou '20' si tu préfères
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Generate static site
        run: npm run generate

      - name: List output (debug)
        run: ls -la .output/public || ls -la dist || echo "Output directory not found"
